# Synthetic assignment data supplied in the Veridian Corp assignment pack.
# Keep this file as the single source of truth for the demo.

POLICIES = [
    {
        "id": "KB-01",
        "title": "Password Reset",
        "text": "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required."
    },
    {
        "id": "KB-02",
        "title": "VPN Access",
        "text": "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee."
    },
    {
        "id": "KB-03",
        "title": "Laptop Replacement",
        "text": "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
    },
    {
        "id": "KB-04",
        "title": "Software Installation Requests",
        "text": "Standard software listed in the approved catalog can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days."
    },
    {
        "id": "KB-05",
        "title": "Printer Troubleshooting",
        "text": "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag."
    },
    {
        "id": "KB-06",
        "title": "Email Mailbox Quota",
        "text": "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB."
    },
    {
        "id": "KB-07",
        "title": "Guest Wi-Fi Access",
        "text": "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required."
    },
    {
        "id": "KB-08",
        "title": "Expense Software Access",
        "text": "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists."
    },
    {
        "id": "KB-09",
        "title": "Security Incident Reporting",
        "text": "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees."
    },
    {
        "id": "KB-10",
        "title": "Work-From-Home Equipment",
        "text": "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved."
    },
    {
        "id": "ASSET",
        "title": "Asset Management Policy (Extract)",
        "text": "Issued by Finance & Assets, last updated Q2 2026. All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."
    }
]

REQUESTS = [
    {"id":"REQ-01","employee":"Aditi Sharma","email":"aditi.sharma@veridian-corp.example","date":"Mon 21 Sep","request":"My laptop won't turn on at all, it's completely dead, had it about 3.5 years now.","initial":"Not started"},
    {"id":"REQ-02","employee":"Vikram Chawla","email":"vikram.chawla@veridian-corp.example","date":"Mon 21 Sep","request":"Can I get Wi-Fi access for a guest visiting our office tomorrow?","initial":"Not started"},
    {"id":"REQ-03","employee":"Karan Mehta","email":"karan.mehta@veridian-corp.example","date":"Mon 21 Sep","request":"I'm locked out of my account, I tried my password 6 times.","initial":"In progress — reset queued"},
    {"id":"REQ-04","employee":"Ritu Bhatia","email":"ritu.bhatia@veridian-corp.example","date":"Tue 22 Sep","request":"Need approval to install a data-analysis tool that's not in the software catalog.","initial":"Waiting on Security review"},
    {"id":"REQ-05","employee":"Sanjay Oberoi","email":"sanjay.oberoi@veridian-corp.example","date":"Tue 22 Sep","request":"My VPN stopped working this morning, says credentials expired.","initial":"Not started"},
    {"id":"REQ-06","employee":"Meera Iyer","email":"meera.iyer@veridian-corp.example","date":"Tue 22 Sep","request":"Printer on the 3rd floor keeps showing 'paper jam' even though there's no jam.","initial":"Investigating — technician assigned"},
    {"id":"REQ-07","employee":"Farhan Ali","email":"farhan.ali@veridian-corp.example","date":"Wed 23 Sep","request":"I've started working from home 4 days a week, how do I get a home office setup?","initial":"Not started"},
    {"id":"REQ-08","employee":"Ananya Reddy","email":"ananya.reddy@veridian-corp.example","date":"Wed 23 Sep","request":"I think I got a phishing email asking for my login — a few teammates got the same email.","initial":"Escalated to Security (info logged)"},
    {"id":"REQ-09","employee":"Rohit Desai","email":"rohit.desai@veridian-corp.example","date":"Wed 23 Sep","request":"My mailbox is full and I can't send emails.","initial":"Not started"},
    {"id":"REQ-10","employee":"Kavya Pillai","email":"kavya.pillai@veridian-corp.example","date":"Wed 23 Sep","request":"Can someone give me admin access to the Finance reporting server? Need it urgently for month-end.","initial":"Not started"},
    {"id":"REQ-11","employee":"Nikhil Bansal","email":"nikhil.bansal@veridian-corp.example","date":"Thu 24 Sep","request":"My contract is ending next month, they'll need VPN access.","initial":"Not started"},
    {"id":"REQ-12","employee":"Sneha Kulkarni","email":"sneha.kulkarni@veridian-corp.example","date":"Thu 24 Sep","request":"I can't log into the expense tool, keeps saying invalid credentials.","initial":"Waiting on employee response (asked for a screenshot, no reply yet)"},
    {"id":"REQ-13","employee":"Aman Gupta","email":"aman.gupta@veridian-corp.example","date":"Thu 24 Sep","request":"Laptop screen is flickering on and off, had it 2 years, maybe just needs a fix not a replacement.","initial":"Not started"},
    {"id":"REQ-14","employee":"Tanya Chopra","email":"tanya.chopra@veridian-corp.example","date":"Fri 25 Sep","request":"Requesting approval to install a browser extension for productivity tracking.","initial":"Not started"},
    {"id":"REQ-15","employee":"Rahul Menon","email":"rahul.menon@veridian-corp.example","date":"Fri 25 Sep","request":"Hey can you help, it's not working.","initial":"Not started"}
]

TICKETS = [
    {"id":"TK-1042","employee":"R. Verma","issue":"VPN credential expired","status":"Resolved (closed)"},
    {"id":"TK-1043","employee":"S. Iyer","issue":"Laptop replacement (3.2 yrs old)","status":"Approved — pending fulfilment (active)"},
    {"id":"TK-1044","employee":"A. Khan","issue":"Non-catalog software request","status":"Pending Security review (active)"},
    {"id":"TK-1045","employee":"P. Joshi","issue":"Mailbox quota increase","status":"Approved at 35GB (closed)"},
    {"id":"TK-1046","employee":"M. Das","issue":"Printer paper jam, floor 2","status":"Resolved (closed)"},
    {"id":"TK-1047","employee":"K. Singh","issue":"Home office equipment request","status":"Pending Finance (active)"},
    {"id":"TK-1048","employee":"T. Rao","issue":"Phishing email reported","status":"Escalated to Security — under investigation (active)"},
    {"id":"TK-1049","employee":"V. Nambiar","issue":"Password reset","status":"Resolved (closed)"},
    {"id":"TK-1050","employee":"J. Fernandes","issue":"Admin access request","status":"Rejected — no business justification provided (closed)"},
    {"id":"TK-1051","employee":"L. Menon","issue":"Guest Wi-Fi issued","status":"Resolved (closed)"}
]
